### PR TITLE
Added Async/Await support via TaskCompletionSource wrappers.

### PR DESCRIPTION
**Pull request by Juiix**

### CODE REVIEW

**Comment by Koushik1029** [comment]
Toxic

**Comment by Juiix** [comment]
> Toxic

?

**Comment by UmarBhatPlaystrom** [comment]
it'd be better if there would be UniTasks

Basically, that's what  I do everytime)

image

**Comment by lupidan** [comment]
Thanks a lot for your time and the proposed Pull Request. 👏 

While I see the value for this particular PR, I think this would better work with some kind of extensions that wraps around the already available code based on callbacks.

Also, I have been trying to avoid "modern C# stuff" such as the `Task` class, so this code can work even in old Unity versions. 

Basically, I believe each game should decide and implement their own Task support around the current functionality.

I'll consider adding `Task` support in some other version.

**Pull request closed without merging**
