### PR TITLE
since PBXCapabilityType ctor was exposed in newer unity versions, trysearching with both public and non-public binding

### PR DESCRIPTION
**Pull request by alexey-unity**

### CODE REVIEW

**Comment by konsnos** [comment]
I was referred to this PR from the Unity forum https://forum.unity.com/threads/project-wont-build-using-xode15-release-candidate.1491761/#post-9350603 , so I expected the code to fix the issue with the missing capability "Sign in with Apple". Unfortunately, that wasn't the case and the Capability wasn't added.

I didn't get any logs of what might be wrong.

**Comment by konsnos** [comment]
I've deleted my previous comment as it was not correctly applied. This code helps resolve the issue of the missing "Sign in with Apple" Capability.

**Comment by lupidan** [comment]
@alexey-unity Thanks for bringing this into my attention.

Moving this to the canary branch to prepare a release.

Also, please notice, I will get this in, **but** I will update the code so it can work up to the latest 2018. I hope that's ok.

**Comment by derwaldgeist** [comment]
@lupidan Great to hear you're already working on this. We're also using your great plugin and stumbled upon this after upgrading to 2022.3.10f1.

**Comment by lupidan** [comment]
It's already out with v1.4.3 👍

**Pull request merged**
